pipeline {
   agent any

   stages {
      stage('Checkout') {
         steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/main']],
                      extensions: [],
                      userRemoteConfigs: [[url: 'https://github.com/waelgharsalliii/ODDO_Project_Automation.git']]])
         }
      }

      stage('Build') {
         steps {
            sh 'cd ODDO_Project && mvn -B compile'
         }
      }

      stage('Test') {
         steps {
            sh 'cd ODDO_Project && mvn -B clean install'
            cucumber failedFeaturesNumber: -1, 
                     failedScenariosNumber: -1, 
                     failedStepsNumber: -1, 
                     fileIncludePattern: '**/*.json', 
                     pendingStepsNumber: -1, 
                     skippedStepsNumber: -1, 
                     sortingMethod: 'ALPHABETICAL', 
                     undefinedStepsNumber: -1
         }
      }
   }

   post {
      always {
         junit '**/target/surefire-reports/*.xml'  // Archive JUnit test results
         cucumber fileIncludePattern: '**/target/cucumber-reports/*.json'  // Archive Cucumber reports
      }
   }
}
