pipeline {
   agent any

   stages {
      stage('Build') {
         steps {
            sh 'cd ODDO_Project && cd mvn -B compile'
         }
      }
      stage('Test'){
          steps{
              sh 'cd ODDO_Project && mvn -B clean install'
              cucumber failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, fileIncludePattern: '**/*.json', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1
              }
      }

   }
}
